/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package farm.dashboard;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppLauncherTest {
    @Test public void testClassExists() {
        AppLauncher classUnderTest = new AppLauncher();
        assertNotNull("You really must have messed up", 1);
    }
}
