/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package farm.dashboard;

public class AppLauncher {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        DashboardApp.main(args);
    }
}
